// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5RGHS4xStnRXILJt446goVgU_V674d6s',
    appId: '1:444663101372:web:337b746ae5e783d96f9db9',
    messagingSenderId: '444663101372',
    projectId: 'flash-notes-f9d53',
    authDomain: 'flash-notes-f9d53.firebaseapp.com',
    storageBucket: 'flash-notes-f9d53.firebasestorage.app',
    measurementId: 'G-1J5YSSSZNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC87wcym0BITA1dcg4ijEZlgg-Kkwc8H7I',
    appId: '1:444663101372:android:9d2233cfc29e003e6f9db9',
    messagingSenderId: '444663101372',
    projectId: 'flash-notes-f9d53',
    storageBucket: 'flash-notes-f9d53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnMCzx-iJ___KNLxARGi104PG-SXzjAUM',
    appId: '1:444663101372:ios:5c466abea20590b26f9db9',
    messagingSenderId: '444663101372',
    projectId: 'flash-notes-f9d53',
    storageBucket: 'flash-notes-f9d53.firebasestorage.app',
    iosBundleId: 'com.example.flashNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnMCzx-iJ___KNLxARGi104PG-SXzjAUM',
    appId: '1:444663101372:ios:5c466abea20590b26f9db9',
    messagingSenderId: '444663101372',
    projectId: 'flash-notes-f9d53',
    storageBucket: 'flash-notes-f9d53.firebasestorage.app',
    iosBundleId: 'com.example.flashNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5RGHS4xStnRXILJt446goVgU_V674d6s',
    appId: '1:444663101372:web:2764370e058fbd166f9db9',
    messagingSenderId: '444663101372',
    projectId: 'flash-notes-f9d53',
    authDomain: 'flash-notes-f9d53.firebaseapp.com',
    storageBucket: 'flash-notes-f9d53.firebasestorage.app',
    measurementId: 'G-W8NXWRYBR9',
  );
}
